"""Generate the static site.

The league updates once a day and is read by five people, so the app does not
need a server: the nightly job runs the pipeline, this writes HTML, and
anything that can serve files serves it. That keeps hosting free and removes
the class of failure where the site is down because a process died.

Pages:

* ``index.html``      -- standings, the progression line, the contribution bars
* ``team/<id>.html``  -- one manager's slots, raw and normalized, with the
                         best-ball selection marked
* ``about.html``      -- how a score is arrived at

Every chart is followed by a table view. That is the accessibility floor, and
also the relief the light-mode palette's contrast warning requires.
"""

from __future__ import annotations

import json
from datetime import date
from html import escape
from pathlib import Path

import pandas as pd

from whul.config.league import (
    ALL_SLOTS, LEAGUE_ABBR, LEAGUE_NAME, SEASON, active_slots, manager_name,
)
from whul.site import charts, images, theme
from whul.store import benchmarks as bm
from whul.store.db import Store

DEFAULT_OUT = Path("site")


def _slug(value: str) -> str:
    return "".join(c if c.isalnum() or c == "-" else "-" for c in value.lower())


#: What the banner says, keyed by what the simulation actually invented. A
#: banner that overstates is a banner nobody reads: once the rosters are real,
#: calling the players placeholders is false on every page.
BANNERS = {
    "everything": (
        "<strong>Simulated data.</strong> These rosters and players are invented "
        "placeholders so the app can be built before the draft is done. Nothing "
        "here is a real result."
    ),
    "scores_only": (
        "<strong>Placeholder scores.</strong> The rosters, players and prices are "
        "real. The scores are invented so the pages can be built before the season "
        "starts — no game has been played yet."
    ),
}


def _page(title: str, body: str, active: str, managers: list[str],
          depth: int = 0, stamp: str = "", simulated: str | bool = False) -> str:
    """One page's HTML. Depth sets how far up the shared assets are."""
    up = "../" * depth
    nav = [("index.html", "Standings"), ("about.html", "How scoring works")]
    current = ' aria-current="page"'
    links = "".join(
        f'<a href="{up}{href}"{current if label == active else ""}>{label}</a>'
        for href, label in nav
    )
    teams = "".join(
        f'<a href="{up}team/{_slug(m)}.html"'
        f'{current if m == active else ""}>{escape(manager_name(m))}</a>'
        for m in managers
    )
    text = BANNERS.get(simulated if isinstance(simulated, str) else "everything")
    banner = f'<div class="banner">{text}</div>' if simulated else ""
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{escape(title)}</title>
<link rel="stylesheet" href="{up}style.css">
</head>
<body>
<div class="wrap">
<header class="masthead">
  <h1><a href="{up}index.html" style="text-decoration:none">
    <span class="full">{escape(LEAGUE_NAME)}</span>
    <span class="short">{escape(LEAGUE_ABBR)}</span>
  </a></h1>
  <span class="stamp">{escape(stamp)}</span>
  <nav>{links}{teams}</nav>
</header>
{banner}
{body}
<footer>
  Generated by <code>python -m whul.cli site</code>. Scores are season-to-date,
  normalized so 100 is the 99th percentile of a draftable pool.
</footer>
</div>
<script src="{up}app.js"></script>
</body>
</html>
"""


def asset_profiles(
    store: Store, season: str, as_of, wanted: set[str], depth: int = 0
) -> dict[str, dict]:
    """Everything the profile window shows, for every asset the page mentions.

    Built once and embedded in the page. On a static site there is nothing to
    fetch from, so a profile has to already be there when it is clicked -- and
    for a few hundred assets that is a smaller payload than one photograph.
    """
    scores = store.query(
        "SELECT asset_id, league_points, scaled_score FROM daily_scores "
        "WHERE season = ? AND as_of = ?",
        (season, str(as_of)),
    ).set_index("asset_id")
    meta = store.query(
        "SELECT asset_id, display_name, league, role, asset_type FROM assets"
    ).set_index("asset_id")
    stats = store.read_stats(season, as_of)

    lines: dict[str, list[tuple[str, str]]] = {}
    finishes: dict[str, list[dict]] = {}
    notes: dict[str, list[str]] = {}
    if not stats.empty:
        for row in stats.to_dict("records"):
            asset_id = row["asset_id"]
            finishes[asset_id] = _finish_list(row)
            notes[asset_id] = _scaling_notes(row)
            lines[asset_id] = _stat_lines(row)

    out: dict[str, dict] = {}
    for asset_id in sorted(wanted):
        if not asset_id or asset_id not in meta.index:
            continue
        info = meta.loc[asset_id]
        name = str(info["display_name"])
        league = str(info["league"])
        badge = images.find("badge", _slug(league))
        out[asset_id] = {
            "name": escape(name),
            "meta": escape(f"{league} · {info['asset_type']}"),
            "avatar": images.avatar("asset", asset_id, name, size=52, depth=depth),
            "badge": (
                f'<img class="badge" src="{"../" * depth}{images.OUT_DIR}/badge/'
                f'{escape(badge.name)}" alt="{escape(league)}">' if badge else ""
            ),
            "raw": f"{float(scores.loc[asset_id, 'league_points']):,.1f}"
                   if asset_id in scores.index else "—",
            "scaled": f"{float(scores.loc[asset_id, 'scaled_score']):,.1f}"
                      if asset_id in scores.index else "—",
            "stats": lines.get(asset_id, []),
            "finishes": finishes.get(asset_id, []),
            "notes": notes.get(asset_id, []),
        }
    return out


#: Columns that identify the row rather than describe the performance, and the
#: two that the window already reports on their own.
STAT_SKIP = {
    "asset_id", "league", "season", "as_of", "source", "phase", "fetched_at",
    "player", "team", "team_name", "display_name", "athlete", "driver",
    "finishes", "norm_key", "asset_type", "role_count", "contract_year",
    "proration_factor", "schedule_factor", "scaled_score", "advanced_share",
}

#: Raw column names read as debug output. These are what they mean.
STAT_LABELS = {
    "total_points": "Total points", "role_points": "Points in this role",
    "events": "Events", "matches": "Matches", "matches_played": "Matches played",
    "games_played": "Games played", "wins": "Wins", "reg_wins": "Regular-season wins",
    "big_wins": "Big wins", "reg_big_wins": "Big wins", "conf_wins": "Conference wins",
    "div_wins": "Division wins", "point_diff": "Point differential",
    "run_diff": "Run differential", "shutouts": "Shutouts",
    "reg_shutouts": "Shutouts", "playoff_app": "Playoff appearance",
    "playoff_appearance": "Playoff appearance", "playoff_wins": "Playoff wins",
    "playoff_game_wins": "Playoff wins", "conf_title_win": "Conference title",
    "pts_reg_champ": "Regular-season title", "div_champ": "Division title",
    "mm_appearance": "NCAA tournament", "mm_wins": "NCAA tournament wins",
    "conf_tourney_wins": "Conference tournament wins",
    "conf_tourney_champ": "Conference tournament title",
    "bye_points": "Bye credit", "appearance_points": "Appearances",
    "goal_points": "Goals", "assists": "Assists", "goals": "Goals",
    "yellow": "Yellow cards", "red": "Red cards", "minutes": "Minutes",
    "starts": "Starts", "races_started": "Races started", "top_tens": "Top tens",
    "made_cut": "Cuts made", "primary_score": "Primary role",
    "secondary_score": "Secondary role", "secondary_role": "Secondary role",
    "is_two_way": "Two-way player",
    "pts_reg_wins": "Regular-season wins", "pts_big_wins": "Big wins",
    "pts_shutouts": "Shutouts", "pts_run_diff": "Run differential",
    "pts_div_champ": "Division title", "pts_playoff": "Postseason",
    "year_n_points": "This season's share", "year_n1_points": "Next season's share",
}


def _label_for(column: str) -> str:
    """A stat's name in words. `games_played` reads as debug output."""
    return STAT_LABELS.get(column, column.replace("_", " ").capitalize())


def _stat_lines(row: dict) -> list[tuple[str, str]]:
    """Every figure that went into the raw score, labelled."""
    out = []
    for column, value in row.items():
        if column in STAT_SKIP or value is None or value != value:
            continue
        if isinstance(value, (list, dict)):
            continue
        if isinstance(value, bool):
            text = "yes" if value else "no"
        elif isinstance(value, float):
            text = f"{value:,.1f}"
        else:
            text = str(value)
        out.append((_label_for(column), text))
    return out


def _finish_list(row: dict) -> list[dict]:
    """The athlete's actual finishes, newest first, where the sport has them."""
    value = row.get("finishes")
    if isinstance(value, str):
        try:
            value = json.loads(value)
        except (TypeError, ValueError):
            return []
    return value if isinstance(value, list) else []


def _scaling_notes(row: dict) -> list[str]:
    """Why a figure here is not simply what the feed reported.

    A score that has been prorated or schedule-scaled looks like an ordinary
    one, and a manager checking the arithmetic against a box score would find
    it does not reconcile. Saying so is cheaper than being asked.
    """
    out = []
    factor = row.get("proration_factor")
    if isinstance(factor, (int, float)) and factor and factor == factor and factor != 1.0:
        out.append(
            f"Counting production is scaled by \u00d7{factor:.3f}, because this "
            f"league year covers a shorter window than the seasons the benchmark "
            f"was drawn from. One-off achievements are not scaled."
        )
    share = row.get("advanced_share")
    if isinstance(share, (int, float)) and share == share and 0 <= share < 1:
        out.append(
            f"Offense, Defense and WAR are shared out across this player's games "
            f"in the window ({share:.0%} of their season so far). The feed "
            f"reports them for the season to date only, and a season of run "
            f"values added to a few weeks of hits would overstate them several "
            f"times over."
        )

    factor = row.get("schedule_factor")
    if isinstance(factor, (int, float)) and factor and factor == factor and factor != 1.0:
        out.append(
            f"The benchmark for this league is lifted by \u00d7{factor:.3f} to "
            f"match a longer schedule than its history was played over."
        )
    return out


def _asset_button(asset_id: str, name: str, counts: bool = True, depth: int = 0) -> str:
    """A name that opens its profile.

    ``counts`` dims the row but does not strike the name. A benched slot's
    *score* is what is set aside; the player is not crossed out, their
    contribution is -- and a struck name reads like a player who has been
    dropped rather than one whose week was someone else's.
    """
    inner = escape(name)
    return (
        f'<button class="assetlink" data-asset="{escape(asset_id or "")}" '
        f'type="button"><span class="who">'
        f'{images.avatar("asset", asset_id, name, size=26, depth=depth)}'
        f'<span class="nm">{inner}</span></span></button>'
    )


def _profile_payload(profiles: dict[str, dict]) -> str:
    return (
        f'<script type="application/json" id="assetdata">{json.dumps(profiles)}</script>'
        '<dialog class="profile" id="profile" aria-label="Asset profile"></dialog>'
    )


def _standings_table(table: pd.DataFrame, mvps: dict[str, str], managers: list[str]) -> str:
    rows = []
    for row in table.itertuples():
        slot = theme.series_index(managers, row.manager_id) + 1
        badge = images.avatar(
            "manager", row.manager_id, row.manager_id,
            size=28, slot=slot, initials=row.manager_id,
        )
        rows.append(
            f"<tr><td class='num'>{row.rank}</td>"
            f"<td><span class='who'>{badge}"
            f"<a href='team/{_slug(row.manager_id)}.html'>"
            f"{escape(manager_name(row.manager_id))}</a></span></td>"
            f"<td class='num'>{row.total:,.1f}</td>"
            f"<td>{mvps.get(row.manager_id, '—')}</td></tr>"
        )
    return (
        "<table><thead><tr><th class='num'>#</th><th>Manager</th>"
        "<th class='num'>Total</th><th>Best performer</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table>"
    )


def _table_view(
    summary: str, header: list[str], rows: list[list[str]],
    columns: list[str] | None = None,
) -> str:
    """A chart's values as a table -- the readable-without-hover fallback.

    ``columns`` names the per-manager columns in order, so hiding a manager in
    the key hides them here too: a reader filtering the chart means the table
    as well, and a table still listing someone the chart has dropped is the
    kind of half-applied filter that gets read as a bug.
    """
    head = "".join(
        f"<th class='num'>{escape(h)}</th>" if i else f"<th>{escape(h)}</th>"
        for i, h in enumerate(header)
    )
    body = "".join(
        "<tr>" + "".join(
            f"<td class='num'>{c}</td>" if i else f"<td>{c}</td>"
            for i, c in enumerate(row)
        ) + "</tr>"
        for row in rows
    )
    named = (
        f' data-columns="{escape(json.dumps(columns))}"' if columns else ""
    )
    return (
        f"<details class='tableview'><summary>{escape(summary)}</summary>"
        f"<table{named}><thead><tr>{head}</tr></thead>"
        f"<tbody>{body}</tbody></table></details>"
    )


def build(
    store: Store,
    season: str,
    out: Path | None = None,
    as_of: date | None = None,
) -> dict:
    """Write the whole site. Returns what it wrote, for the CLI to report."""
    from whul import pipeline

    out = Path(out or DEFAULT_OUT)

    progression = pipeline.progression(store, season)
    if progression.empty:
        raise ValueError(_why_no_standings(store, season))

    # Only once there is something to write. Creating it first left an empty
    # `team/` behind on every failed build, which a local server then served as
    # a directory listing -- a site that looks built and is not.
    (out / "team").mkdir(parents=True, exist_ok=True)

    latest = as_of or progression["as_of"].max()
    today = progression[progression["as_of"] == latest].sort_values("rank")
    managers = sorted(progression["manager_id"].unique())
    slotted = [(manager_name(m), theme.series_index(managers, m) + 1) for m in managers]
    simulated = store.scalar(
        "SELECT key FROM admin_overrides WHERE scope = 'simulation' AND season = ? "
        "ORDER BY set_at DESC LIMIT 1",
        (season,),
    ) or False
    version = bm.active_version(store, season)
    stamp = f"{season} · through {latest}"

    bars = pipeline.contributions(store, season, latest)
    counting = bars[bars["counts"] == 1] if not bars.empty else bars
    slot_counts = (
        counting.groupby("manager_id").size().to_dict() if not counting.empty else {}
    )

    (out / "style.css").write_text(theme.STYLESHEET)
    (out / "app.js").write_text(charts.SCRIPT)
    photos = images.copy_all(out)

    rostered = set(bars["asset_id"].dropna()) if not bars.empty else set()
    profiles = asset_profiles(store, season, latest, rostered)
    deep_profiles = asset_profiles(store, season, latest, rostered, depth=1)

    _write_index(out, season, today, progression, bars, managers, slotted,
                 latest, stamp, simulated, profiles)
    for manager in managers:
        _write_team(out, manager, managers, bars, store, season, latest, stamp,
                    simulated, deep_profiles)
    _write_about(out, managers, stamp, simulated, version,
                 _uncovered(store, season, version))

    return {
        "out": str(out),
        "season": season,
        "as_of": str(latest),
        "pages": 2 + len(managers),
        "managers": len(managers),
        "days": int(progression["as_of"].nunique()),
        "simulated": simulated,
        "photos": photos,
        "profiles": len(profiles),
    }


def _why_no_standings(store, season: str) -> str:
    """Which link in the chain is missing, rather than that the chain is.

    Every step depends on the one before, so "no standings" is the symptom of
    four different problems. Naming the first one that is actually missing is
    the difference between a message and an instruction.
    """
    from whul.store import benchmarks as bm

    lines = [f"No standings for {season}, so there is nothing to build yet."]

    rostered = store.scalar(
        "SELECT COUNT(*) FROM slot_occupancy o "
        "JOIN roster_slots s ON s.slot_id = o.slot_id WHERE s.season = ?",
        (season,),
    ) or 0
    scores = store.scalar(
        "SELECT COUNT(*) FROM daily_scores WHERE season = ?", (season,)
    ) or 0
    frozen = bm.active_version(store, season)

    if not rostered:
        lines.append(
            f"  Nothing is rostered in {season}. Import the draft: "
            f"`python -m whul.cli import-rosters --write --season {season}`"
        )
    elif frozen is None:
        lines.append(
            f"  {rostered} slots are filled, but no benchmark version is frozen "
            f"for {season}, so nothing can be placed on the 0-100 scale.\n"
            f"  `python -m whul.cli benchmarks versions`, then "
            f"`benchmarks freeze <version>`."
        )
    elif not scores:
        lines.append(
            f"  Benchmark {frozen.version} is frozen and {rostered} slots are "
            f"filled, but no results have been recorded.\n"
            f"  `python -m whul.cli ingest --season {season}`"
        )
    else:
        lines.append(
            f"  {scores} scores are recorded but no day has been rolled up.\n"
            f"  `python -m whul.cli rollup --season {season}`"
        )
    lines.append(
        f"  For a placeholder league instead: `python -m whul.cli simulate`."
    )
    return "\n".join(lines)


def _slot_rows(bars: pd.DataFrame, managers: list[str]) -> tuple[list, dict, dict]:
    """Rank each manager's slots within a category, so a row compares like with like.

    Row "NFL 1" is every manager's best NFL slot, "NFL 2" their second, and so
    on. Ranking rather than using the stored slot index matters because a slot
    index is arbitrary -- best ball reorders them constantly -- so comparing
    slot 1 to slot 1 would compare nothing in particular.
    """
    order = []
    seen: set[str] = set()
    for group in active_slots(ALL_SLOTS):
        if group.category not in seen:
            seen.add(group.category)
            order.append(group.category)

    depth = {}
    for group in active_slots(ALL_SLOTS):
        depth[group.category] = depth.get(group.category, 0) + group.starters

    values: dict[tuple[str, str], tuple[float, str, str]] = {}
    counting = bars[bars["counts"] == 1] if not bars.empty else bars
    for manager in managers:
        mine = counting[counting["manager_id"] == manager] if not counting.empty else counting
        for category in order:
            block = mine[mine["category"] == category] if not mine.empty else mine
            # An undrafted slot has no score to rank and no bar to draw, so
            # it is dropped here -- the row still exists on the chart, it just
            # has nothing in it for this manager.
            if not block.empty:
                block = block[block["asset_id"].notna() & (block["asset_id"] != "")]
            ranked = block.sort_values("score", ascending=False) if not block.empty else block
            for rank, row in enumerate(ranked.itertuples(), start=1):
                values[(manager_name(manager), f"{category} {rank}")] = (
                    float(row.score), str(row.asset_id or ""), ""
                )

    # The key stays fully qualified so two categories cannot collide, but the
    # row shows only its rank -- the category is already the run's heading, and
    # repeating it eight times is eight lines of the same words.
    rows = [
        (category, f"{category} {rank}", f"#{rank}")
        for category in order
        for rank in range(1, depth.get(category, 0) + 1)
    ]
    return rows, values, depth


def _write_index(out, season, today, progression, bars, managers, slotted,
                 latest, stamp, simulated, profiles) -> None:
    leader = today.iloc[0]
    margin = float(today.iloc[0]["total"] - today.iloc[1]["total"]) if len(today) > 1 else 0.0

    # Who has gained most in the last week -- the standings say who is ahead,
    # this says who is coming. A ceiling nobody approaches said neither.
    week = sorted(progression["as_of"].unique())
    earlier = week[max(0, len(week) - 8)]
    gains = {}
    for manager in managers:
        run = progression[progression["manager_id"] == manager].set_index("as_of")
        if latest in run.index and earlier in run.index:
            gains[manager] = float(run.loc[latest, "total"] - run.loc[earlier, "total"])
    riser, gain = max(gains.items(), key=lambda kv: kv[1]) if gains else ("—", 0.0)

    counting = bars[bars["counts"] == 1] if not bars.empty else bars
    mvps = {}
    for manager in managers:
        mine = counting[counting["manager_id"] == manager] if not counting.empty else counting
        if not mine.empty:
            mine = mine[mine["asset_id"].notna() & (mine["asset_id"] != "")]
        if mine.empty:
            continue
        best = mine.sort_values("score", ascending=False).iloc[0]
        asset_id = str(best["asset_id"] or "")
        profile = profiles.get(asset_id)
        name = profile["name"] if profile else asset_id or "—"
        mvps[manager] = (
            f'<button class="assetlink" type="button" data-asset="{escape(asset_id)}">'
            f'<span class="who">'
            f'{images.avatar("asset", asset_id, name, size=26)}'
            f'<span><span class="nm">{name}</span> '
            f'<span style="color:var(--muted)">{best["category"]} · '
            f'{float(best["score"]):,.1f}</span></span></span></button>'
        )

    tiles = f"""
<div class="grid2" style="margin-bottom:22px">
  <div class="tile"><div class="label">Leader</div>
    <div class="value">{escape(manager_name(str(leader['manager_id'])))}</div>
    <div class="note">{leader['total']:,.1f} points, {margin:,.1f} clear</div></div>
  <div class="tile"><div class="label">Biggest riser this week</div>
    <div class="value">{escape(manager_name(str(riser)))}</div>
    <div class="note">+{gain:,.1f} in the last 7 days</div></div>
  <div class="tile"><div class="label">Season</div>
    <div class="value">{escape(season)}</div>
    <div class="note">through {latest}</div></div>
</div>"""

    days = sorted(progression["as_of"].unique())
    series = []
    for (manager, slot), key in zip(slotted, managers):
        run = progression[progression["manager_id"] == key].set_index("as_of")
        series.append(charts.Series(
            name=manager, slot=slot,
            values=[float(run.loc[d, "total"]) if d in run.index else 0.0 for d in days],
        ))

    sampled = days[:: max(1, len(days) // 14)] or days
    if days[-1] not in sampled:
        sampled.append(days[-1])
    progression_rows = [
        [str(d)] + [f"{s.values[days.index(d)]:,.1f}" for s in series] for d in sampled
    ]

    slot_rows, values, slot_depth = _slot_rows(bars, managers)
    # Name each bar's asset, so the tooltip and the table both read as people.
    for key, (score, asset_id, _) in list(values.items()):
        profile = profiles.get(asset_id)
        values[key] = (score, asset_id, profile["name"] if profile else "")
    bar_rows = [
        [key] + [
            (f"{values[(m, key)][0]:,.1f}" if (m, key) in values else "—")
            for m, _ in slotted
        ]
        for _, key, _ in slot_rows
    ]

    body = f"""
{tiles}
<div class="card">
  <h2>Standings</h2>
  <p class="sub">Season-to-date, best ball: each manager's counting slots only.
    Click a name to see how a score was arrived at.</p>
  {_standings_table(today, mvps, managers)}
</div>

<div class="card">
  <h2>Progression</h2>
  <p class="sub">Total score by day. Hover for every manager on a given date.</p>
  {charts.legend(slotted, filterable=True)}
  {charts.progression_chart(days, series)}
  {_table_view("Show as a table", ["Date"] + [s.name for s in series],
               progression_rows, columns=[s.name for s in series])}
</div>

<div class="card">
  <h2>Every counting slot</h2>
  <p class="sub">One section per league, each collapsible. A manager's slots sit
    together in their own colour, ranked best first, so a category reads as a
    block. Every bar is a single normalized score, so any two are directly
    comparable. Click a manager in the key to hide them; click a bar for the
    player behind it.</p>
  {charts.legend(slotted, filterable=True)}
  {charts.slot_sections(slot_rows, slotted, values, depth=slot_depth)}
  {_table_view("Show as a table", ["Slot"] + [m for m, _ in slotted], bar_rows,
               columns=[m for m, _ in slotted])}
</div>
{_profile_payload(profiles)}
"""
    (out / "index.html").write_text(
        _page(f"{LEAGUE_ABBR} — Standings", body, "Standings", managers,
              stamp=stamp, simulated=simulated)
    )


def _write_team(out, manager, managers, bars, store, season, latest, stamp,
                simulated, profiles) -> None:
    """One manager's roster: every slot, with the normalized score it is worth.

    The raw score and the stat lines behind it live in the profile window
    rather than in the table -- there are sixty slots, and a column of raw
    numbers on a scale that differs per league compares nothing to anything.
    """
    mine = bars[bars["manager_id"] == manager] if not bars.empty else bars
    raw = store.query(
        "SELECT asset_id, league_points, scaled_score FROM daily_scores "
        "WHERE season = ? AND as_of = ?",
        (season, str(latest)),
    ).set_index("asset_id")

    sections = []
    total = 0.0
    empty_slots = 0
    for asset_type in ("Player", "Team"):
        rows = []
        block = mine[mine["asset_type"] == asset_type] if not mine.empty else mine
        if block.empty:
            continue
        for category in sorted(block["category"].unique()):
            for row in block[block["category"] == category].sort_values(
                "score", ascending=False
            ).itertuples():
                asset = str(row.asset_id or "")
                # An undrafted slot is shown, not skipped. It is a slot the
                # manager still has to fill, and hiding it would make a roster
                # with a hole look complete.
                if not asset:
                    empty_slots += 1
                    rows.append(
                        f"<tr class='empty'>"
                        f"<td class='slotname'>{escape(category)}</td>"
                        f"<td class='undrafted'>Undrafted</td>"
                        f"<td class='num'>—</td></tr>"
                    )
                    continue
                profile = profiles.get(asset)
                name = profile["name"] if profile else asset
                scaled = float(raw.loc[asset, "scaled_score"]) if asset in raw.index else 0.0
                counts = bool(row.counts)
                total += float(row.score) if counts else 0.0
                # A benched slot's score is struck through rather than hidden:
                # it is what the slot would be worth, and seeing it is how a
                # manager knows how close the bench is to the cut.
                value = (
                    f"{scaled:,.1f}" if counts
                    else f'<span class="struck">{scaled:,.1f}</span>'
                )
                rows.append(
                    f"<tr class='{'' if counts else 'bench'}'>"
                    f"<td class='slotname'>{escape(category)}</td>"
                    f"<td>{_asset_button(asset, name, counts, depth=1)}</td>"
                    f"<td class='num'>{value}</td></tr>"
                )
        sections.append(
            f"<div class='card'><h2>{asset_type}s</h2>"
            f"<p class='sub'>Normalized score, where 100 is the 99th percentile of a "
            f"draftable pool. Benched slots are struck through. Click a name for the "
            f"raw stats behind the score.</p>"
            "<table><thead><tr><th>Category</th><th>Asset</th>"
            "<th class='num'>Normalized</th></tr></thead>"
            f"<tbody>{''.join(rows)}</tbody></table></div>"
        )

    slot = theme.series_index(managers, manager) + 1
    head = f"""
<div class="grid2" style="margin-bottom:22px">
  <div class="tile"><div class="label">Manager</div>
    <div class="value"><span class="who">
      {images.avatar("manager", manager, manager, size=38, slot=slot,
                     depth=1, initials=manager)}
      {escape(manager_name(manager))}</span></div></div>
  <div class="tile"><div class="label">Counting total</div>
    <div class="value">{total:,.1f}</div>
    <div class="note">on {latest}</div></div>
  <div class="tile"><div class="label">Still to draft</div>
    <div class="value">{empty_slots}</div>
    <div class="note">{"every slot filled" if not empty_slots else "slots with nobody in them"}</div></div>
</div>"""
    (out / "team" / f"{_slug(manager)}.html").write_text(
        _page(f"{LEAGUE_ABBR} — {manager_name(manager)}", head + "".join(sections) +
              _profile_payload(profiles), manager,
              managers, depth=1, stamp=stamp, simulated=simulated)
    )


def _uncovered(store, season: str, version) -> list[tuple[str, str, int]]:
    """Rostered league/type pairs the active benchmark cannot score.

    A standing built while a league has no benchmark is not wrong, but it is
    partial, and it looks exactly like a complete one: the managers holding
    those picks are simply lower. Saying so on the page is the difference
    between a season in progress and a season being misreported.
    """
    from whul import benchmarks as benchmark_method

    if version is None:
        return []
    try:
        table = benchmark_method.coverage(store, version.version, season)
    except Exception:  # noqa: BLE001 -- a note on a page must never fail a build
        return []
    if table.empty or "covered" not in table.columns:
        return []
    missing = table[~table["covered"].astype(bool)]
    return [
        (str(row.league), str(row.asset_type), int(row.assets))
        for row in missing.itertuples()
    ]


def _write_about(out, managers, stamp, simulated, version, uncovered=()) -> None:
    groups = "".join(
        f"<tr><td>{escape(g.asset_type)}</td><td>{escape(g.category)}</td>"
        f"<td class='num'>{g.cap}</td><td class='num'>{g.starters}</td></tr>"
        for g in active_slots(ALL_SLOTS)
    )
    body = f"""
<div class="card">
  <h2>How a score is arrived at</h2>
  <p class="sub">Four steps, in order.</p>
  <table><tbody>
    <tr><td><strong>1. League points</strong></td><td>Each league's own formula, from
      the R scripts — half-PPR for the NFL, ATP ranking points for tennis, and so on.</td></tr>
    <tr><td><strong>2. Normalize</strong></td><td>Divided by a frozen benchmark and
      multiplied by 100, so 100 is the 99th percentile of a draftable pool in that
      position group. Above 100 is meaningful, not an error.</td></tr>
    <tr><td><strong>3. Accrue by owner</strong></td><td>A slot's score is what each
      occupant earned while it sat there, so a trade leaves points with the manager
      who earned them.</td></tr>
    <tr><td><strong>4. Best ball</strong></td><td>Each category counts its top K slots.
      Nothing to set: the selection moves on its own as scores move.</td></tr>
  </tbody></table>
</div>

<div class="card">
  <h2>The roster</h2>
  <p class="sub">{sum(g.cap for g in active_slots(ALL_SLOTS))} slots,
    {sum(g.starters for g in active_slots(ALL_SLOTS))} of them counting.</p>
  <table><thead><tr><th>Type</th><th>Category</th>
    <th class='num'>Slots</th><th class='num'>Counting</th></tr></thead>
    <tbody>{groups}</tbody></table>
</div>

<div class="card">
  <h2>Benchmarks</h2>
  <p class="sub">Frozen before the season and reused unchanged, so standings never
    silently rewrite themselves.</p>
  <p>Active version: <code>{escape(version.version) if version else 'none'}</code>
    {f'— frozen {escape(version.frozen_at)}' if version and version.frozen_at else ''}</p>
  {_uncovered_note(uncovered)}
</div>
"""
    (out / "about.html").write_text(
        _page(f"{LEAGUE_ABBR} — How scoring works", body, "How scoring works", managers,
              stamp=stamp, simulated=simulated)
    )


def _uncovered_note(uncovered) -> str:
    """The part of the roster today's standings cannot yet speak for."""
    if not uncovered:
        return ""
    rows = "".join(
        f"<tr><td>{escape(league)}</td><td>{escape(kind.lower())}s</td>"
        f"<td class='num'>{count}</td></tr>"
        for league, kind, count in uncovered
    )
    total = sum(count for _, _, count in uncovered)
    return f"""
  <p class="sub">Not yet scored: {total} rostered pick(s) in leagues this
    version has no benchmark for. They score nothing until one is computed, so
    the managers holding them are shown lower than they will finish.</p>
  <table><thead><tr><th>League</th><th>Type</th>
    <th class='num'>Picks</th></tr></thead><tbody>{rows}</tbody></table>"""
