"""Generate the static site.

The league updates once a day and is read by five people, so the app does not
need a server: the nightly job runs the pipeline, this writes HTML, and
anything that can serve files serves it. That keeps hosting free and removes
the class of failure where the site is down because a process died.

Pages:

* ``index.html``      -- standings, the progression line, the contribution bars
* ``team/<id>.html``  -- one manager's slots, raw and normalized, with the
                         best-ball selection marked
* ``about.html``      -- how a score is arrived at

Every chart is followed by a table view. That is the accessibility floor, and
also the relief the light-mode palette's contrast warning requires.
"""

from __future__ import annotations

import json
from datetime import date
from html import escape
from pathlib import Path

import pandas as pd

from whul.config.league import (
    ALL_SLOTS, LEAGUE_ABBR, LEAGUE_NAME, SEASON, active_slots, manager_name,
)
from whul.site import charts, images, theme
from whul.store import benchmarks as bm
from whul.store.db import Store

DEFAULT_OUT = Path("site")


def _slug(value: str) -> str:
    return "".join(c if c.isalnum() or c == "-" else "-" for c in value.lower())


#: What the banner says, keyed by what the simulation actually invented. A
#: banner that overstates is a banner nobody reads: once the rosters are real,
#: calling the players placeholders is false on every page.
BANNERS = {
    "everything": (
        "<strong>Simulated data.</strong> These rosters and players are invented "
        "placeholders so the app can be built before the draft is done. Nothing "
        "here is a real result."
    ),
    "scores_only": (
        "<strong>Placeholder scores.</strong> The rosters, players and prices are "
        "real. The scores are invented so the pages can be built before the season "
        "starts — no game has been played yet."
    ),
}


def _page(title: str, body: str, active: str, managers: list[str],
          depth: int = 0, stamp: str = "", simulated: str | bool = False) -> str:
    """One page's HTML. Depth sets how far up the shared assets are."""
    up = "../" * depth
    nav = [("index.html", "Standings"), ("results.html", "Results"),
           ("about.html", "How scoring works")]
    current = ' aria-current="page"'
    links = "".join(
        f'<a href="{up}{href}"{current if label == active else ""}>{label}</a>'
        for href, label in nav
    )
    teams = "".join(
        f'<a href="{up}team/{_slug(m)}.html"'
        f'{current if m == active else ""}>{escape(manager_name(m))}</a>'
        for m in managers
    )
    text = BANNERS.get(simulated if isinstance(simulated, str) else "everything")
    banner = f'<div class="banner">{text}</div>' if simulated else ""
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{escape(title)}</title>
<link rel="stylesheet" href="{up}style.css">
</head>
<body>
<div class="wrap">
<header class="masthead">
  <h1><a href="{up}index.html" style="text-decoration:none">{escape(LEAGUE_NAME)}</a></h1>
  <span class="stamp">{escape(stamp)}</span>
  <nav>{links}{teams}</nav>
</header>
{banner}
{body}
<footer>
  Generated by <code>python -m whul.cli site</code>. Scores are season-to-date,
  normalized so 100 is the 99th percentile of a draftable pool.
</footer>
</div>
<script src="{up}app.js"></script>
</body>
</html>
"""


#: Roster categories whose picks are individuals rather than club employees.
#: Their affiliation is a country, and the corner of their picture is a flag.
INDIVIDUAL_CATEGORIES = {"Tennis", "PGA", "Motorsports", "Olympics"}


def _identity(stats: dict, league: str, norm_key: str,
              affiliation: str = "") -> dict[str, str]:
    """What a player is, out of the day's recorded row.

    Three lines, and each is only shown when it says something:

    ``position``  what the player plays -- "F", "Batter", "Driver". The feed
                  calls it ``position`` where it has one and ``role`` where the
                  distinction is the sport itself, and either answers the
                  question a reader is asking.
    ``team``      the club or franchise. This is what tells two players with one
                  surname apart, which no amount of statistics does.
    ``group``     the benchmark group the 0-100 was measured against, which is
                  the position group where a sport has them. Suppressed when it
                  merely repeats the league: an italic line reading "Premier
                  League" under a line reading "Premier League" is furniture.
    """
    def first(*names: str, words_only: bool = False) -> str:
        for name in names:
            value = stats.get(name)
            if value is None or value != value:      # NaN
                continue
            text = str(value).strip()
            if not text or text.lower() in ("nan", "none"):
                continue
            # A position is a word. Golf files a *finishing* position under the
            # same key -- Rory McIlroy read "14.0 · Northern Ireland", which is
            # a place on a leaderboard printed where a role belongs. Skipping
            # the number falls through to the role, which says "Golfer".
            if words_only and text.replace(".", "").replace("-", "").isdigit():
                continue
            return text
        return ""

    group = norm_key.replace("_", " ").strip()
    return {
        "position": first("position", "role", words_only=True),
        # The feed first, then the sheet. The feed is the one that notices a
        # January transfer; the sheet is the one that knows a golfer is Spanish,
        # which no feed here carries at all. Neither covers the other's case, so
        # both are read and the fresher wins where they overlap.
        "team": first("team_name", "team", "club") or affiliation.strip(),
        "group": "" if group in ("", league) else group,
    }


#: Which confederation a national side belongs to, for the shield in its
#: corner. Written down because nothing in the roster carries it and no feed
#: here does either: a country's continent is not a fact about a football
#: match, so it has to be stated.
#:
#: Not exhaustive, and does not pretend to be. It covers the nations a slot in
#: this league plausibly holds; anything else gets no corner badge, which is
#: the honest answer -- a wrong shield is worse than none, and adding a line
#: here is a smaller job than noticing a quiet mistake.
CONFEDERATIONS = {
    "uefa": (
        "England", "France", "Spain", "Germany", "Italy", "Portugal",
        "Netherlands", "Belgium", "Croatia", "Denmark", "Sweden", "Norway",
        "Switzerland", "Austria", "Poland", "Ukraine", "Serbia", "Scotland",
        "Wales", "Republic of Ireland", "Ireland", "Czechia", "Czech Republic",
        "Turkey", "Greece", "Russia", "Hungary", "Romania", "Iceland",
        "Finland", "Slovakia", "Slovenia", "Albania", "Bosnia and Herzegovina",
        "North Macedonia", "Georgia", "Northern Ireland",
    ),
    "conmebol": (
        "Brazil", "Argentina", "Uruguay", "Colombia", "Chile", "Peru",
        "Ecuador", "Paraguay", "Bolivia", "Venezuela",
    ),
    "concacaf": (
        "USA", "United States", "Mexico", "Canada", "Costa Rica", "Jamaica",
        "Panama", "Honduras", "El Salvador", "Haiti", "Trinidad and Tobago",
    ),
    "caf": (
        "Morocco", "Senegal", "Nigeria", "Egypt", "Ghana", "Cameroon",
        "Algeria", "Tunisia", "Ivory Coast", "South Africa", "Mali",
    ),
    "afc": (
        "Japan", "South Korea", "Australia", "Iran", "Saudi Arabia", "Qatar",
        "China", "Iraq", "Uzbekistan", "Jordan",
    ),
    "ofc": ("New Zealand", "Fiji", "New Caledonia"),
}

#: Country -> confederation, built once from the table above.
CONFEDERATION_OF = {
    country: shield
    for shield, countries in CONFEDERATIONS.items()
    for country in countries
}


def corner_badge(asset_type: str, category: str, league: str,
                 affiliation: str) -> tuple[str, str] | None:
    """The image that goes bottom-right of this asset's picture.

    ``(directory, filename stem)``, or None where nothing is known to put
    there. Which directory it is follows from what the asset is, so there is
    nothing to choose and nothing to keep in step:

        a team-sport player   his club's crest
        an individual athlete their country's flag
        a club or programme   its league's mark
        an international side its confederation's shield
        an Olympic entry      the rings

    The main picture is always ``asset/<asset id>``. This is only the corner.
    """
    if asset_type == "Team":
        if "Intl" in category:
            shield = CONFEDERATION_OF.get(affiliation.strip())
            return ("shield", shield) if shield else None
        if category == "Olympics":
            return ("shield", "olympics")
        return ("badge", _slug(league)) if league else None
    if category in INDIVIDUAL_CATEGORIES:
        return ("flag", _slug(affiliation)) if affiliation else None
    return ("club", _slug(affiliation)) if affiliation else None


def badge_names(store: Store, season: str, as_of=None) -> dict[str, str]:
    """What to badge each asset with, keyed by asset id.

    The feed's spelling first, the spreadsheet's second -- the same precedence
    the profile line uses, and for the same reason twice over.

    The feed notices a transfer, which the sheet only does when somebody
    remembers. And the feed's name is ESPN's own, so a crest looked up under it
    matches by construction: the sheet said "Los Angeles Clippers" and ESPN
    files them as "LA Clippers", so a perfectly correct name found nothing at
    all. Preferring the feed makes that class of miss impossible wherever the
    feed has an answer, and the sheet stays the answer where it does not --
    every golfer's country, and every league that has not kicked off.

    A club that changes spelling between the two therefore changes the crest's
    filename too. The old file goes stale rather than wrong; the fetch writes
    the new one and nothing points at the old.
    """
    day = as_of or store.scalar(
        "SELECT MAX(as_of) FROM raw_stats WHERE season = ?", (season,)
    )
    from_feed: dict[str, dict] = {}
    if day:
        stats = store.read_stats(season, day)
        if not stats.empty:
            from_feed = {row["asset_id"]: row for row in stats.to_dict("records")}

    rows = store.query(
        "SELECT DISTINCT a.asset_id, a.league, a.norm_key, a.affiliation "
        "FROM roster_slots r "
        "JOIN slot_occupancy o ON o.slot_id = r.slot_id AND o.end_date IS NULL "
        "JOIN assets a ON a.asset_id = o.asset_id "
        "WHERE r.season = ?", (season,),
    )
    out: dict[str, str] = {}
    for row in rows.itertuples():
        who = _identity(
            from_feed.get(row.asset_id, {}), str(row.league or ""),
            str(row.norm_key or ""), str(row.affiliation or ""),
        )
        if who["team"]:
            out[str(row.asset_id)] = who["team"]
    return out


def asset_profiles(
    store: Store, season: str, as_of, wanted: set[str], depth: int = 0
) -> dict[str, dict]:
    """Everything the profile window shows, for every asset the page mentions.

    Built once and embedded in the page. On a static site there is nothing to
    fetch from, so a profile has to already be there when it is clicked -- and
    for a few hundred assets that is a smaller payload than one photograph.
    """
    scores = store.query(
        "SELECT asset_id, league_points, scaled_score FROM daily_scores "
        "WHERE season = ? AND as_of = ?",
        (season, str(as_of)),
    ).set_index("asset_id")
    meta = store.query(
        "SELECT asset_id, display_name, league, role, norm_key, affiliation, "
        "asset_type FROM assets"
    ).set_index("asset_id")
    stats = store.read_stats(season, as_of)
    # The roster category, which is what decides whether a corner badge is a
    # club, a flag or a shield. It lives on the slot rather than the asset,
    # since the same country can be a men's and a women's side.
    categories = dict(store.query(
        "SELECT DISTINCT o.asset_id, r.category FROM roster_slots r "
        "JOIN slot_occupancy o ON o.slot_id = r.slot_id AND o.end_date IS NULL "
        "WHERE r.season = ?", (season,),
    ).itertuples(index=False, name=None))

    lines: dict[str, list[tuple[str, str]]] = {}
    finishes: dict[str, list[dict]] = {}
    notes: dict[str, list[str]] = {}
    raw_rows: dict[str, dict] = {}
    if not stats.empty:
        for row in stats.to_dict("records"):
            asset_id = row["asset_id"]
            finishes[asset_id] = _finish_list(row)
            notes[asset_id] = _scaling_notes(row)
            lines[asset_id] = _stat_lines(row)
            raw_rows[asset_id] = row

    out: dict[str, dict] = {}
    for asset_id in sorted(wanted):
        if not asset_id or asset_id not in meta.index:
            continue
        info = meta.loc[asset_id]
        name = str(info["display_name"])
        league = str(info["league"])
        badge = images.find("badge", _slug(league))
        who = _identity(
            raw_rows.get(asset_id, {}), league, str(info["norm_key"] or ""),
            str(info["affiliation"] or ""),
        )
        corner = corner_badge(
            str(info["asset_type"]), categories.get(asset_id, ""), league,
            who["team"],
        )
        out[asset_id] = {
            "name": escape(name),
            "meta": escape(f"{league} · {info['asset_type']}"),
            # Each on its own, as well as in the line the window prints. A
            # table cell shows the position and the club and not the rest, and
            # splitting a formatted string back up to get at them is how the
            # two drift apart.
            "position": escape(who["position"]),
            "team": escape(who["team"]),
            "group": escape(who["group"]),
            # Carried so the tables can badge a name without working out again
            # what this already knows. Two derivations of one rule drift.
            "corner": list(corner) if corner else None,
            # A team's picture is a crest and is fitted rather than cropped;
            # carried for the same reason as the corner, so a table does not
            # have to know what an asset type implies.
            "logo": str(info["asset_type"]) == "Team",
            # Kept apart from `meta` as well as in it: the chart labels a bar
            # with the kind alone, and splitting a formatted string back up to
            # get at it is how the two drift.
            "kind": escape(str(info["asset_type"])),
            "league": escape(league),
            "avatar": images.avatar("asset", asset_id, name, size=52, depth=depth,
                                    badge=corner,
                                    logo=str(info["asset_type"]) == "Team"),
            "badge": (
                f'<img class="badge" src="{"../" * depth}{images.OUT_DIR}/badge/'
                f'{escape(badge.name)}" alt="{escape(league)}">' if badge else ""
            ),
            "raw": f"{float(scores.loc[asset_id, 'league_points']):,.1f}"
                   if asset_id in scores.index else "—",
            "scaled": f"{float(scores.loc[asset_id, 'scaled_score']):,.1f}"
                      if asset_id in scores.index else "—",
            "stats": lines.get(asset_id, []),
            "finishes": finishes.get(asset_id, []),
            "notes": notes.get(asset_id, []),
        }
    return out


#: Columns that identify the row rather than describe the performance, and the
#: two that the window already reports on their own.
STAT_SKIP = {
    "asset_id", "league", "season", "as_of", "source", "phase", "fetched_at",
    "player", "team", "team_name", "display_name", "athlete", "driver",
    "finishes", "norm_key", "asset_type", "role_count", "contract_year",
    "proration_factor", "schedule_factor", "scaled_score", "advanced_share",
    # Shown as identity, above the figures. Left here as well they read as a
    # statistic -- "Position  F" in a column of goals and assists.
    "position", "role",
}

#: Raw column names read as debug output. These are what they mean.
STAT_LABELS = {
    "total_points": "Total points", "role_points": "Points in this role",
    "events": "Events", "matches": "Matches", "matches_played": "Matches played",
    "games_played": "Games played", "wins": "Wins", "reg_wins": "Regular-season wins",
    "big_wins": "Big wins", "reg_big_wins": "Big wins", "conf_wins": "Conference wins",
    "div_wins": "Division wins", "point_diff": "Point differential",
    "run_diff": "Run differential", "shutouts": "Shutouts",
    "reg_shutouts": "Shutouts", "playoff_app": "Playoff appearance",
    "playoff_appearance": "Playoff appearance", "playoff_wins": "Playoff wins",
    "playoff_game_wins": "Playoff wins", "conf_title_win": "Conference title",
    "pts_reg_champ": "Regular-season title", "div_champ": "Division title",
    "mm_appearance": "NCAA tournament", "mm_wins": "NCAA tournament wins",
    "conf_tourney_wins": "Conference tournament wins",
    "conf_tourney_champ": "Conference tournament title",
    "bye_points": "Bye credit", "appearance_points": "Appearances",
    "goal_points": "Goals", "assists": "Assists", "goals": "Goals",
    "yellow": "Yellow cards", "red": "Red cards", "minutes": "Minutes",
    "starts": "Starts", "races_started": "Races started", "top_tens": "Top tens",
    "made_cut": "Cuts made", "primary_score": "Primary role",
    "secondary_score": "Secondary role", "secondary_role": "Secondary role",
    "is_two_way": "Two-way player",
    "pts_reg_wins": "Regular-season wins", "pts_big_wins": "Big wins",
    "pts_shutouts": "Shutouts", "pts_run_diff": "Run differential",
    "pts_div_champ": "Division title", "pts_playoff": "Postseason",
    "year_n_points": "This season's share", "year_n1_points": "Next season's share",
}


def _label_for(column: str) -> str:
    """A stat's name in words. `games_played` reads as debug output."""
    return STAT_LABELS.get(column, column.replace("_", " ").capitalize())


def _stat_lines(row: dict) -> list[tuple[str, str]]:
    """Every figure that went into the raw score, labelled."""
    out = []
    for column, value in row.items():
        if column in STAT_SKIP or value is None or value != value:
            continue
        if isinstance(value, (list, dict)):
            continue
        if isinstance(value, bool):
            text = "yes" if value else "no"
        elif isinstance(value, float):
            text = f"{value:,.1f}"
        else:
            text = str(value)
        out.append((_label_for(column), text))
    return out


def _finish_list(row: dict) -> list[dict]:
    """The athlete's actual finishes, newest first, where the sport has them."""
    value = row.get("finishes")
    if isinstance(value, str):
        try:
            value = json.loads(value)
        except (TypeError, ValueError):
            return []
    return value if isinstance(value, list) else []


def _scaling_notes(row: dict) -> list[str]:
    """Why a figure here is not simply what the feed reported.

    A score that has been prorated or schedule-scaled looks like an ordinary
    one, and a manager checking the arithmetic against a box score would find
    it does not reconcile. Saying so is cheaper than being asked.
    """
    out = []
    factor = row.get("proration_factor")
    if isinstance(factor, (int, float)) and factor and factor == factor and factor != 1.0:
        out.append(
            f"Counting production is scaled by \u00d7{factor:.3f}, because this "
            f"league year covers a shorter window than the seasons the benchmark "
            f"was drawn from. One-off achievements are not scaled."
        )
    share = row.get("advanced_share")
    if isinstance(share, (int, float)) and share == share and 0 <= share < 1:
        out.append(
            f"Offense, Defense and WAR are shared out across this player's games "
            f"in the window ({share:.0%} of their season so far). The feed "
            f"reports them for the season to date only, and a season of run "
            f"values added to a few weeks of hits would overstate them several "
            f"times over."
        )

    factor = row.get("schedule_factor")
    if isinstance(factor, (int, float)) and factor and factor == factor and factor != 1.0:
        out.append(
            f"The benchmark for this league is lifted by \u00d7{factor:.3f} to "
            f"match a longer schedule than its history was played over."
        )
    return out


def _identity_lines(profile: dict | None, *tail: str) -> str:
    """The grey lines under a name: what they play, where, and against what.

    ``tail`` is whatever the caller wants on the end of the first line -- the
    league, usually, which a roster table already says in its own column and a
    results table does not.

    Empty parts are dropped rather than left as stray separators. Most of these
    are empty most of the season: a league that has not started has recorded no
    row, so there is no position and no club to show, and a page of names each
    followed by " · " would look broken rather than early.
    """
    if not profile:
        return ""
    parts = [p for p in (profile.get("position", ""), profile.get("team", ""),
                         *tail) if p]
    out = f'<span class="idl">{" · ".join(parts)}</span>' if parts else ""
    group = profile.get("group", "")
    return out + (f'<em class="grp">{group}</em>' if group else "")


def _asset_button(asset_id: str, name: str, counts: bool = True, depth: int = 0,
                  profile: dict | None = None) -> str:
    """A name that opens its profile, with what the name is underneath it.

    ``counts`` dims the row but does not strike the name. A benched slot's
    *score* is what is set aside; the player is not crossed out, their
    contribution is -- and a struck name reads like a player who has been
    dropped rather than one whose week was someone else's.

    The position and club go here rather than only in the window because a
    roster is sixty names and reading it should not need sixty clicks. The
    window still has all of it, which is what the click is for.
    """
    inner = escape(name)
    corner = profile.get("corner") if profile else None
    corner = tuple(corner) if corner else None
    logo = bool(profile.get("logo")) if profile else False
    return (
        f'<button class="assetlink" data-asset="{escape(asset_id or "")}" '
        f'type="button"><span class="who">'
        f"{images.avatar('asset', asset_id, name, size=26, depth=depth, badge=corner, logo=logo)}"
        f'<span class="stack"><span class="nm">{inner}</span>'
        f'{_identity_lines(profile)}</span></span></button>'
    )


def _counting_mix(
    mine: pd.DataFrame, profiles: dict[str, dict]
) -> list[tuple[str, list[tuple[str, float, str]]]]:
    """A manager's counting slots, grouped by category, biggest share first.

    Past six segments a part-to-whole figure stops being readable -- angles
    cannot be compared and adjacent hues blur -- so the tail folds into one
    "Other". A manager has nine contributing categories now and will have twice
    that once every league is in season, which the table beneath is for.
    """
    if mine.empty:
        return []
    counting = mine[mine["counts"].astype(bool) & (mine["score"] > 0)]
    if counting.empty:
        return []

    by_category: dict[str, list[tuple[str, float, str]]] = {}
    for row in counting.sort_values("score", ascending=False).itertuples():
        asset = str(row.asset_id or "")
        profile = profiles.get(asset)
        name = profile["name"] if profile else asset
        by_category.setdefault(str(row.category), []).append(
            (name, float(row.score), asset)
        )

    ranked = sorted(
        by_category.items(),
        key=lambda kv: sum(score for _, score, _ in kv[1]),
        reverse=True,
    )
    if len(ranked) <= charts.DONUT_SEGMENTS:
        return ranked
    head = ranked[:charts.DONUT_SEGMENTS - 1]
    tail = [h for _, holdings in ranked[charts.DONUT_SEGMENTS - 1:] for h in holdings]
    return head + [(charts.DONUT_OTHER, sorted(tail, key=lambda h: -h[1]))]


def _season_note(live: int, filled: int) -> str:
    """What the counting total is missing, said in the tile that shows it.

    A total of 1,900 in September and one of 4,000 in March are not a team
    improving; they are eleven leagues in season instead of five. The tile
    printed the date and left the reader to know that.
    """
    if not filled:
        return "nothing drafted yet"
    if live == filled:
        return "every slot in season"
    return f"{live} of {filled} slots in season"


def _in_season(
    mine: pd.DataFrame, profiles: dict[str, dict], day: date
) -> tuple[int, int]:
    """How many of a manager's counting slots are in a league that has started.

    Returns ``(in season, filled)``. The difference between the two is what a
    total is missing today, and it is the whole reason a counting total in
    September cannot be compared with one in February.

    Asked of the calendar rather than of the scores. A slot whose player is
    injured, benched, suspended or simply had a quiet week scores zero, and
    counting non-zero scores would file all of that under "not started" -- so a
    manager whose NFL back is hurt would look like a manager who has not
    drafted one. The league has started; the slot is in it; the zero is a
    result.

    The exception is a slot with no start date to ask about, which today is
    only the international squads: each plays in a different competition on a
    different calendar. There a score is the only evidence there is, so a zero
    is read as "the tournaments have not come round yet" -- the reading this
    function exists to avoid everywhere else, used here because nothing better
    exists.
    """
    from whul.config.league import in_season as league_in_season

    if mine.empty:
        return 0, 0
    filled = mine[mine["counts"].astype(bool) & mine["asset_id"].astype(bool)]
    if filled.empty:
        return 0, 0

    live = 0
    for row in filled.itertuples():
        profile = profiles.get(str(row.asset_id)) or {}
        started = league_in_season(str(profile.get("league") or ""), day)
        live += bool(float(row.score) > 0) if started is None else bool(started)
    return live, len(filled)


def _results_table(
    bars: pd.DataFrame, profiles: dict[str, dict], managers: list[str]
) -> str:
    """Every scored asset in one table, best first.

    The bar chart answers "how is my roster doing"; this answers "who is doing
    well", which is a different question and had no page. Sorted by normalized
    score because that is the only figure comparable across leagues -- a raw
    total is on a scale that differs per sport.

    Filtered in the browser rather than pre-split: twenty leagues is twenty
    tables nobody scrolls, and the interesting comparison is usually across two
    of them rather than within one.
    """
    if bars.empty:
        return '<p class="sub">Nothing scored yet.</p>'

    rows = []
    leagues: set[str] = set()
    kinds: set[str] = set()
    for row in bars.sort_values("score", ascending=False).itertuples():
        profile = profiles.get(row.asset_id)
        if not profile:
            continue
        league = profile.get("league", "")
        kind = profile.get("kind", "")
        leagues.add(league)
        kinds.add(kind)
        slot = theme.series_index(managers, row.manager_id) + 1
        rows.append(
            f'<tr data-league="{league}" data-kind="{kind}">'
            f'<td><button class="assetlink" data-asset="{escape(row.asset_id)}">'
            f'{profile["name"]}</button>'
            f'<span class="rowmeta">{_identity_lines(profile, league, kind)}</span>'
            f'</td>'
            f'<td><span class="who"><i class="swatch" '
            f'style="background: var(--series-{slot})"></i>'
            f'{escape(manager_name(row.manager_id))}</span></td>'
            f'<td class="num" data-score="{row.score:.4f}">{row.score:,.1f}</td></tr>'
        )
    if not rows:
        return '<p class="sub">Nothing scored yet.</p>'

    def chips(name: str, values: set[str]) -> str:
        buttons = "".join(
            f'<button class="chip" data-filter="{name}" data-value="{escape(v)}" '
            f'aria-pressed="false">{escape(v)}</button>'
            for v in sorted(values) if v
        )
        return f'<div class="chips" role="group" aria-label="Filter by {name}">{buttons}</div>'

    # Everything is listed, including the assets on nothing yet -- two thirds
    # of the roster in September, when most leagues have not started. Listing
    # them is the honest default and burying them is the useful one, so the
    # toggle is here and off, rather than either being chosen for the reader.
    scoring_only = (
        '<div class="chips" role="group" aria-label="Hide unscored">'
        '<button class="chip" data-filter="scoring" data-value="yes" '
        'aria-pressed="false">Scoring only</button></div>'
    )
    return (
        f'{chips("kind", kinds)}{chips("league", leagues)}{scoring_only}'
        '<p class="sub filtercount" data-count>Showing every scored asset.</p>'
        '<table class="results" id="resultstable">'
        '<thead><tr><th>Asset</th><th>Owner</th>'
        '<th class="num">Normalized</th></tr></thead>'
        f'<tbody>{"".join(rows)}</tbody></table>'
    )


def _figure(anchor: str, title: str, blurb: str, body: str, open_: bool = True) -> str:
    """One collapsible figure, addressable by anchor.

    Open by default and remembered per reader, like the league boxes: a page of
    three closed figures makes someone open the one they came for every time,
    and a page of three open ones is long. Letting them choose once is the only
    answer that suits both.
    """
    return f"""
<details class="figure" id="{anchor}" data-figure="{anchor}"{" open" if open_ else ""}>
  <summary><h2>{escape(title)}</h2></summary>
  <div class="figurebody">
    <p class="sub">{blurb}</p>
    {body}
  </div>
</details>"""


def _figure_index(items: list[tuple[str, str]]) -> str:
    """Links to the figures below, so the page opens with a way through it."""
    links = "".join(
        f'<a class="jump" href="#{anchor}">{escape(label)}</a>' for anchor, label in items
    )
    return f'<nav class="figureindex" aria-label="On this page">{links}</nav>'


def _profile_payload(profiles: dict[str, dict]) -> str:
    return (
        f'<script type="application/json" id="assetdata">{json.dumps(profiles)}</script>'
        '<dialog class="profile" id="profile" aria-label="Asset profile"></dialog>'
    )


def _standings_table(table: pd.DataFrame, mvps: dict[str, str], managers: list[str]) -> str:
    rows = []
    for row in table.itertuples():
        slot = theme.series_index(managers, row.manager_id) + 1
        badge = images.avatar(
            "manager", row.manager_id, row.manager_id,
            size=28, slot=slot, initials=row.manager_id,
        )
        rows.append(
            f"<tr><td class='num'>{row.rank}</td>"
            f"<td><span class='who'>{badge}"
            f"<a href='team/{_slug(row.manager_id)}.html'>"
            f"{escape(manager_name(row.manager_id))}</a></span></td>"
            f"<td class='num'>{row.total:,.1f}</td>"
            f"<td>{mvps.get(row.manager_id, '—')}</td></tr>"
        )
    return (
        "<table><thead><tr><th class='num'>#</th><th>Manager</th>"
        "<th class='num'>Total</th><th>Best performer</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table>"
    )


def _table_view(
    summary: str, header: list[str], rows: list[list[str]],
    columns: list[str] | None = None,
) -> str:
    """A chart's values as a table -- the readable-without-hover fallback.

    ``columns`` names the per-manager columns in order, so hiding a manager in
    the key hides them here too: a reader filtering the chart means the table
    as well, and a table still listing someone the chart has dropped is the
    kind of half-applied filter that gets read as a bug.
    """
    head = "".join(
        f"<th class='num'>{escape(h)}</th>" if i else f"<th>{escape(h)}</th>"
        for i, h in enumerate(header)
    )
    body = "".join(
        "<tr>" + "".join(
            f"<td class='num'>{c}</td>" if i else f"<td>{c}</td>"
            for i, c in enumerate(row)
        ) + "</tr>"
        for row in rows
    )
    named = (
        f' data-columns="{escape(json.dumps(columns))}"' if columns else ""
    )
    return (
        f"<details class='tableview'><summary>{escape(summary)}</summary>"
        f"<table{named}><thead><tr>{head}</tr></thead>"
        f"<tbody>{body}</tbody></table></details>"
    )


def build(
    store: Store,
    season: str,
    out: Path | None = None,
    as_of: date | None = None,
) -> dict:
    """Write the whole site. Returns what it wrote, for the CLI to report."""
    from whul import pipeline

    out = Path(out or DEFAULT_OUT)

    progression = pipeline.progression(store, season)
    if progression.empty:
        raise ValueError(_why_no_standings(store, season))

    # Only once there is something to write. Creating it first left an empty
    # `team/` behind on every failed build, which a local server then served as
    # a directory listing -- a site that looks built and is not.
    (out / "team").mkdir(parents=True, exist_ok=True)

    latest = as_of or progression["as_of"].max()
    today = progression[progression["as_of"] == latest].sort_values("rank")
    managers = sorted(progression["manager_id"].unique())
    slotted = [(manager_name(m), theme.series_index(managers, m) + 1) for m in managers]
    simulated = store.scalar(
        "SELECT key FROM admin_overrides WHERE scope = 'simulation' AND season = ? "
        "ORDER BY set_at DESC LIMIT 1",
        (season,),
    ) or False
    version = bm.active_version(store, season)
    stamp = f"{season} · through {latest}"

    bars = pipeline.contributions(store, season, latest)
    counting = bars[bars["counts"] == 1] if not bars.empty else bars
    slot_counts = (
        counting.groupby("manager_id").size().to_dict() if not counting.empty else {}
    )

    (out / "style.css").write_text(theme.STYLESHEET)
    (out / "app.js").write_text(charts.SCRIPT)
    photos = images.copy_all(out)

    rostered = set(bars["asset_id"].dropna()) if not bars.empty else set()
    profiles = asset_profiles(store, season, latest, rostered)
    deep_profiles = asset_profiles(store, season, latest, rostered, depth=1)

    _write_index(out, season, today, progression, bars, managers, slotted,
                 latest, stamp, simulated, profiles)
    for manager in managers:
        _write_team(out, manager, managers, bars, store, season, latest, stamp,
                    simulated, deep_profiles)
    _write_about(out, managers, stamp, simulated, version,
                 _uncovered(store, season, version))

    return {
        "out": str(out),
        "season": season,
        "as_of": str(latest),
        "pages": 2 + len(managers),
        "managers": len(managers),
        "days": int(progression["as_of"].nunique()),
        "simulated": simulated,
        "photos": photos,
        "profiles": len(profiles),
    }


def _why_no_standings(store, season: str) -> str:
    """Which link in the chain is missing, rather than that the chain is.

    Every step depends on the one before, so "no standings" is the symptom of
    four different problems. Naming the first one that is actually missing is
    the difference between a message and an instruction.
    """
    from whul.store import benchmarks as bm

    lines = [f"No standings for {season}, so there is nothing to build yet."]

    rostered = store.scalar(
        "SELECT COUNT(*) FROM slot_occupancy o "
        "JOIN roster_slots s ON s.slot_id = o.slot_id WHERE s.season = ?",
        (season,),
    ) or 0
    scores = store.scalar(
        "SELECT COUNT(*) FROM daily_scores WHERE season = ?", (season,)
    ) or 0
    frozen = bm.active_version(store, season)

    if not rostered:
        lines.append(
            f"  Nothing is rostered in {season}. Import the draft: "
            f"`python -m whul.cli import-rosters --write --season {season}`"
        )
    elif frozen is None:
        lines.append(
            f"  {rostered} slots are filled, but no benchmark version is frozen "
            f"for {season}, so nothing can be placed on the 0-100 scale.\n"
            f"  `python -m whul.cli benchmarks versions`, then "
            f"`benchmarks freeze <version>`."
        )
    elif not scores:
        lines.append(
            f"  Benchmark {frozen.version} is frozen and {rostered} slots are "
            f"filled, but no results have been recorded.\n"
            f"  `python -m whul.cli ingest --season {season}`"
        )
    else:
        lines.append(
            f"  {scores} scores are recorded but no day has been rolled up.\n"
            f"  `python -m whul.cli rollup --season {season}`"
        )
    lines.append(
        f"  For a placeholder league instead: `python -m whul.cli simulate`."
    )
    return "\n".join(lines)


def _slot_rows(bars: pd.DataFrame, managers: list[str]) -> tuple[list, dict, dict]:
    """Rank each manager's slots within a category, so a row compares like with like.

    Row "NFL 1" is every manager's best NFL slot, "NFL 2" their second, and so
    on. Ranking rather than using the stored slot index matters because a slot
    index is arbitrary -- best ball reorders them constantly -- so comparing
    slot 1 to slot 1 would compare nothing in particular.
    """
    order = []
    seen: set[str] = set()
    for group in active_slots(ALL_SLOTS):
        if group.category not in seen:
            seen.add(group.category)
            order.append(group.category)

    depth = {}
    for group in active_slots(ALL_SLOTS):
        depth[group.category] = depth.get(group.category, 0) + group.starters

    values: dict[tuple[str, str], tuple[float, str, str]] = {}
    counting = bars[bars["counts"] == 1] if not bars.empty else bars
    for manager in managers:
        mine = counting[counting["manager_id"] == manager] if not counting.empty else counting
        for category in order:
            block = mine[mine["category"] == category] if not mine.empty else mine
            # An undrafted slot has no score to rank and no bar to draw, so
            # it is dropped here -- the row still exists on the chart, it just
            # has nothing in it for this manager.
            if not block.empty:
                block = block[block["asset_id"].notna() & (block["asset_id"] != "")]
            ranked = block.sort_values("score", ascending=False) if not block.empty else block
            for rank, row in enumerate(ranked.itertuples(), start=1):
                values[(manager_name(manager), f"{category} {rank}")] = (
                    float(row.score), str(row.asset_id or ""), ""
                )

    # The key stays fully qualified so two categories cannot collide, but the
    # row shows only its rank -- the category is already the run's heading, and
    # repeating it eight times is eight lines of the same words.
    rows = [
        (category, f"{category} {rank}", f"#{rank}")
        for category in order
        for rank in range(1, depth.get(category, 0) + 1)
    ]
    return rows, values, depth


def _write_index(out, season, today, progression, bars, managers, slotted,
                 latest, stamp, simulated, profiles) -> None:
    leader = today.iloc[0]
    margin = float(today.iloc[0]["total"] - today.iloc[1]["total"]) if len(today) > 1 else 0.0

    # Who has gained most in the last week -- the standings say who is ahead,
    # this says who is coming. A ceiling nobody approaches said neither.
    week = sorted(progression["as_of"].unique())
    earlier = week[max(0, len(week) - 8)]
    gains = {}
    for manager in managers:
        run = progression[progression["manager_id"] == manager].set_index("as_of")
        if latest in run.index and earlier in run.index:
            gains[manager] = float(run.loc[latest, "total"] - run.loc[earlier, "total"])
    riser, gain = max(gains.items(), key=lambda kv: kv[1]) if gains else ("—", 0.0)

    counting = bars[bars["counts"] == 1] if not bars.empty else bars
    mvps = {}
    for manager in managers:
        mine = counting[counting["manager_id"] == manager] if not counting.empty else counting
        if not mine.empty:
            mine = mine[mine["asset_id"].notna() & (mine["asset_id"] != "")]
        if mine.empty:
            continue
        best = mine.sort_values("score", ascending=False).iloc[0]
        asset_id = str(best["asset_id"] or "")
        profile = profiles.get(asset_id)
        name = profile["name"] if profile else asset_id or "—"
        corner = (profile or {}).get("corner")
        corner = tuple(corner) if corner else None
        is_logo = bool((profile or {}).get("logo"))
        mvps[manager] = (
            f'<button class="assetlink" type="button" data-asset="{escape(asset_id)}">'
            f'<span class="who">'
            f"{images.avatar('asset', asset_id, name, size=26, badge=corner, logo=is_logo)}"
            f'<span><span class="nm">{name}</span> '
            f'<span style="color:var(--muted)">{best["category"]} · '
            f'{float(best["score"]):,.1f}</span></span></span></button>'
        )

    tiles = f"""
<div class="grid2" style="margin-bottom:22px">
  <div class="tile"><div class="label">Leader</div>
    <div class="value">{escape(manager_name(str(leader['manager_id'])))}</div>
    <div class="note">{leader['total']:,.1f} points, {margin:,.1f} clear</div></div>
  <div class="tile"><div class="label">Biggest riser this week</div>
    <div class="value">{escape(manager_name(str(riser)))}</div>
    <div class="note">+{gain:,.1f} in the last 7 days</div></div>
  <div class="tile"><div class="label">Season</div>
    <div class="value">{escape(season)}</div>
    <div class="note">through {latest}</div></div>
</div>"""

    days = sorted(progression["as_of"].unique())
    series = []
    for (manager, slot), key in zip(slotted, managers):
        run = progression[progression["manager_id"] == key].set_index("as_of")
        series.append(charts.Series(
            name=manager, slot=slot,
            values=[float(run.loc[d, "total"]) if d in run.index else 0.0 for d in days],
        ))

    sampled = days[:: max(1, len(days) // 14)] or days
    if days[-1] not in sampled:
        sampled.append(days[-1])
    progression_rows = [
        [str(d)] + [f"{s.values[days.index(d)]:,.1f}" for s in series] for d in sampled
    ]

    slot_rows, values, slot_depth = _slot_rows(bars, managers)
    # Name each bar's asset, so the tooltip and the table both read as people.
    # The kind rides along, which is what lets a bar say "Arsenal Team" rather
    # than "Club Soccer Top 3 1".
    for key, (score, asset_id, _) in list(values.items()):
        profile = profiles.get(asset_id)
        values[key] = (
            score, asset_id,
            profile["name"] if profile else "",
            profile.get("kind", "") if profile else "",
        )
    bar_rows = [
        [key] + [
            (f"{values[(m, key)][0]:,.1f}" if (m, key) in values else "—")
            for m, _ in slotted
        ]
        for _, key, _ in slot_rows
    ]

    body = f"""
{tiles}
<div class="card">
  <h2>Standings</h2>
  <p class="sub">Season-to-date, best ball: each manager's counting slots only.
    Click a name to see how a score was arrived at.</p>
  {_standings_table(today, mvps, managers)}
</div>

<div class="card">
  <h2>Progression</h2>
  <p class="sub">Total score by day. Hover for every manager on a given date.</p>
  {charts.legend(slotted, filterable=True)}
  {charts.progression_chart(days, series)}
  {_table_view("Show as a table", ["Date"] + [s.name for s in series],
               progression_rows, columns=[s.name for s in series])}
</div>

{_profile_payload(profiles)}
"""
    (out / "index.html").write_text(
        _page(f"{LEAGUE_ABBR} — Standings", body, "Standings", managers,
              stamp=stamp, simulated=simulated)
    )

    # --- results ------------------------------------------------------------
    # The bar chart moves here and the progression is copied. Copied rather
    # than moved because the standings page is what someone opens to see who is
    # winning, and the line is the shape of that; the bars are the detail
    # underneath it, which is what this page is for.
    progression_figure = _figure(
        "progression", "Progression",
        "Total score by day. Hover for every manager on a given date.",
        f"{charts.legend(slotted, filterable=True)}"
        f"{charts.progression_chart(days, series)}"
        + _table_view("Show as a table", ["Date"] + [s.name for s in series],
                      progression_rows, columns=[s.name for s in series]),
    )
    slots_figure = _figure(
        "slots", "Every counting slot",
        "One section per league, each collapsible. A manager's slots sit "
        "together in their own colour, ranked best first, so a category reads "
        "as a block. Every bar is a single normalized score, so any two are "
        "directly comparable. Click a manager in the key to hide them; click a "
        "bar for the asset behind it.",
        f"{charts.legend(slotted, filterable=True)}"
        f"{charts.slot_sections(slot_rows, slotted, values, depth=slot_depth)}"
        + _table_view("Show as a table", ["Slot"] + [m for m, _ in slotted],
                      bar_rows, columns=[m for m, _ in slotted]),
    )
    table_figure = _figure(
        "everyone", "Every scored asset",
        "Best first, on the normalized scale -- the only figure comparable "
        "across leagues. Filter by kind or league; the filters combine. Click "
        "a name for the stats behind the score.",
        _results_table(bars, profiles, managers),
    )
    results_body = (
        _figure_index([("progression", "Progression"),
                       ("slots", "Every counting slot"),
                       ("everyone", "Every scored asset")])
        + progression_figure + slots_figure + table_figure
        + _profile_payload(profiles)
    )
    (out / "results.html").write_text(
        _page(f"{LEAGUE_ABBR} — Results", results_body, "Results", managers,
              stamp=stamp, simulated=simulated)
    )


def _write_team(out, manager, managers, bars, store, season, latest, stamp,
                simulated, profiles) -> None:
    """One manager's roster: every slot, with the normalized score it is worth.

    The raw score and the stat lines behind it live in the profile window
    rather than in the table -- there are sixty slots, and a column of raw
    numbers on a scale that differs per league compares nothing to anything.
    """
    mine = bars[bars["manager_id"] == manager] if not bars.empty else bars
    raw = store.query(
        "SELECT asset_id, league_points, scaled_score FROM daily_scores "
        "WHERE season = ? AND as_of = ?",
        (season, str(latest)),
    ).set_index("asset_id")

    sections = []
    total = 0.0
    empty_slots = 0
    for asset_type in ("Player", "Team"):
        rows = []
        block = mine[mine["asset_type"] == asset_type] if not mine.empty else mine
        if block.empty:
            continue
        for category in sorted(block["category"].unique()):
            for row in block[block["category"] == category].sort_values(
                "score", ascending=False
            ).itertuples():
                asset = str(row.asset_id or "")
                # An undrafted slot is shown, not skipped. It is a slot the
                # manager still has to fill, and hiding it would make a roster
                # with a hole look complete.
                if not asset:
                    empty_slots += 1
                    rows.append(
                        f"<tr class='empty'>"
                        f"<td class='slotname'>{escape(category)}</td>"
                        f"<td class='undrafted'>Undrafted</td>"
                        f"<td class='num'>—</td></tr>"
                    )
                    continue
                profile = profiles.get(asset)
                name = profile["name"] if profile else asset
                scaled = float(raw.loc[asset, "scaled_score"]) if asset in raw.index else 0.0
                counts = bool(row.counts)
                total += float(row.score) if counts else 0.0
                # A benched slot's score is struck through rather than hidden:
                # it is what the slot would be worth, and seeing it is how a
                # manager knows how close the bench is to the cut.
                value = (
                    f"{scaled:,.1f}" if counts
                    else f'<span class="struck">{scaled:,.1f}</span>'
                )
                rows.append(
                    f"<tr class='{'' if counts else 'bench'}'>"
                    f"<td class='slotname'>{escape(category)}</td>"
                    f"<td>{_asset_button(asset, name, counts, depth=1, profile=profile)}</td>"
                    f"<td class='num'>{value}</td></tr>"
                )
        sections.append(
            f"<div class='card'><h2>{asset_type}s</h2>"
            f"<p class='sub'>Normalized score, where 100 is the 99th percentile of a "
            f"draftable pool. Benched slots are struck through. Click a name for the "
            f"raw stats behind the score.</p>"
            "<table><thead><tr><th>Category</th><th>Asset</th>"
            "<th class='num'>Normalized</th></tr></thead>"
            f"<tbody>{''.join(rows)}</tbody></table></div>"
        )

    slot = theme.series_index(managers, manager) + 1

    # The count of unfilled slots used to be a tile of its own. It is one
    # number that changes a handful of times a season, and it sat beside two
    # others in the space where the interesting question is which parts of the
    # roster are carrying the total. The count keeps its place in the sentence
    # under the ring, where it is still read and no longer costs a third of the
    # header.
    mix = _counting_mix(mine, profiles)
    live, filled = _in_season(mine, profiles, latest)
    still = (
        "Every slot filled." if not empty_slots
        else f"{empty_slots} slot{'' if empty_slots == 1 else 's'} still to draft."
    )
    mix_card = (
        f'<div class="card"><h2>Where the total comes from</h2>'
        f'<p class="sub">Each roster category is one colour and the assets '
        f'inside it step down in shade, biggest first. Hover a segment for the '
        f'asset, click it for the stats behind the score. {escape(still)}</p>'
        f'<div class="mix">{charts.donut_chart(mix, total)}</div></div>'
    )

    head = f"""
<div class="grid2" style="margin-bottom:22px">
  <div class="tile"><div class="label">Manager</div>
    <div class="value"><span class="who">
      {images.avatar("manager", manager, manager, size=38, slot=slot,
                     depth=1, initials=manager)}
      {escape(manager_name(manager))}</span></div></div>
  <div class="tile"><div class="label">Counting total</div>
    <div class="value">{total:,.1f}</div>
    <div class="note">on {latest} · {_season_note(live, filled)}</div></div>
</div>{mix_card}"""
    (out / "team" / f"{_slug(manager)}.html").write_text(
        _page(f"{LEAGUE_ABBR} — {manager_name(manager)}", head + "".join(sections) +
              _profile_payload(profiles), manager,
              managers, depth=1, stamp=stamp, simulated=simulated)
    )


def _uncovered(store, season: str, version) -> list[tuple[str, str, int]]:
    """Rostered league/type pairs the active benchmark cannot score.

    A standing built while a league has no benchmark is not wrong, but it is
    partial, and it looks exactly like a complete one: the managers holding
    those picks are simply lower. Saying so on the page is the difference
    between a season in progress and a season being misreported.
    """
    from whul import benchmarks as benchmark_method

    if version is None:
        return []
    try:
        table = benchmark_method.coverage(store, version.version, season)
    except Exception:  # noqa: BLE001 -- a note on a page must never fail a build
        return []
    if table.empty or "covered" not in table.columns:
        return []
    missing = table[~table["covered"].astype(bool)]
    return [
        (str(row.league), str(row.asset_type), int(row.assets))
        for row in missing.itertuples()
    ]


def _write_about(out, managers, stamp, simulated, version, uncovered=()) -> None:
    groups = "".join(
        f"<tr><td>{escape(g.asset_type)}</td><td>{escape(g.category)}</td>"
        f"<td class='num'>{g.cap}</td><td class='num'>{g.starters}</td></tr>"
        for g in active_slots(ALL_SLOTS)
    )
    body = f"""
<div class="card">
  <h2>How a score is arrived at</h2>
  <p class="sub">Four steps, in order.</p>
  <table><tbody>
    <tr><td><strong>1. League points</strong></td><td>Each league's own formula, from
      the R scripts — half-PPR for the NFL, ATP ranking points for tennis, and so on.</td></tr>
    <tr><td><strong>2. Normalize</strong></td><td>Divided by a frozen benchmark and
      multiplied by 100, so 100 is the 99th percentile of a draftable pool in that
      position group. Above 100 is meaningful, not an error.</td></tr>
    <tr><td><strong>3. Accrue by owner</strong></td><td>A slot's score is what each
      occupant earned while it sat there, so a trade leaves points with the manager
      who earned them.</td></tr>
    <tr><td><strong>4. Best ball</strong></td><td>Each category counts its top K slots.
      Nothing to set: the selection moves on its own as scores move.</td></tr>
  </tbody></table>
</div>

<div class="card">
  <h2>The roster</h2>
  <p class="sub">{sum(g.cap for g in active_slots(ALL_SLOTS))} slots,
    {sum(g.starters for g in active_slots(ALL_SLOTS))} of them counting.</p>
  <table><thead><tr><th>Type</th><th>Category</th>
    <th class='num'>Slots</th><th class='num'>Counting</th></tr></thead>
    <tbody>{groups}</tbody></table>
</div>

<div class="card">
  <h2>Benchmarks</h2>
  <p class="sub">Frozen before the season and reused unchanged, so standings never
    silently rewrite themselves.</p>
  <p>Active version: <code>{escape(version.version) if version else 'none'}</code>
    {f'— frozen {escape(version.frozen_at)}' if version and version.frozen_at else ''}</p>
  {_uncovered_note(uncovered)}
</div>
"""
    (out / "about.html").write_text(
        _page(f"{LEAGUE_ABBR} — How scoring works", body, "How scoring works", managers,
              stamp=stamp, simulated=simulated)
    )


def _uncovered_note(uncovered) -> str:
    """The part of the roster today's standings cannot yet speak for."""
    if not uncovered:
        return ""
    rows = "".join(
        f"<tr><td>{escape(league)}</td><td>{escape(kind.lower())}s</td>"
        f"<td class='num'>{count}</td></tr>"
        for league, kind, count in uncovered
    )
    total = sum(count for _, _, count in uncovered)
    return f"""
  <p class="sub">Not yet scored: {total} rostered pick(s) in leagues this
    version has no benchmark for. They score nothing until one is computed, so
    the managers holding them are shown lower than they will finish.</p>
  <table><thead><tr><th>League</th><th>Type</th>
    <th class='num'>Picks</th></tr></thead><tbody>{rows}</tbody></table>"""
