"""What turns the site into something with its own home-screen icon.

A manifest, a service worker and a set of icons. Between them they mean a
manager can install the league from their phone's browser and open it from the
home screen without a tab -- which is the whole of what was asked for. There is
no app store in this, no wrapper, no build step and no developer account: a
progressive web app is the same static files with three more of them.

The service worker is the part worth being careful about. This site's only
claim is that it is current, so a cache that served yesterday's standings
would break the one thing it does. Every request goes to the network first and
the cache is a fallback for when there is no network at all -- the opposite of
the usual advice, and right here: a page that loads a second slower is a minor
cost, and a page that quietly shows Tuesday's table on Thursday is not.
"""

from __future__ import annotations

import json

from whul.config.league import LEAGUE_ABBR, LEAGUE_NAME

#: The colour a phone paints its own furniture with -- the status bar behind a
#: standalone window. One per scheme, matching the page underneath it.
THEME_LIGHT = "#f9f9f7"
THEME_DARK = "#0d0d0d"


def manifest() -> str:
    """The web app manifest, as JSON.

    Every URL in it is relative. The site is served from a project path on
    GitHub Pages today and could be served from a domain root tomorrow, and a
    manifest that hard-coded either would install an app pointing at nothing.
    Relative URLs resolve against the manifest's own address, which is correct
    in both cases without being told which one it is.
    """
    return json.dumps({
        "name": LEAGUE_NAME,
        "short_name": LEAGUE_ABBR,
        "description": f"{LEAGUE_NAME} standings, results and records.",
        "start_url": ".",
        "scope": ".",
        "display": "standalone",
        "orientation": "portrait-primary",
        "theme_color": THEME_LIGHT,
        "background_color": THEME_DARK,
        "icons": [
            {"src": "icon-192.png", "sizes": "192x192", "type": "image/png"},
            {"src": "icon-512.png", "sizes": "512x512", "type": "image/png"},
            # Cropped to whatever shape the launcher likes. The icon is drawn
            # with a wide margin so a circular crop takes only the ground.
            {"src": "icon-512.png", "sizes": "512x512", "type": "image/png",
             "purpose": "maskable"},
        ],
    }, indent=2)


def service_worker(version: str) -> str:
    """The service worker, stamped with the build it came from.

    The stamp is the cache's name, so every publish starts a fresh one and the
    old is deleted on activation. Without it a worker installed in October
    would still be answering from an October cache in March, and the reader
    would have no way to know.
    """
    safe = json.dumps(str(version or "0"))
    return f"""\
// Generated by whul.site.pwa. Do not edit here.
//
// Network first, always. This site's only claim is that it is current, so the
// cache exists for the case where there is no network at all -- a plane, a
// lift, a dead spot -- and never to save a round trip.
const VERSION = {safe};
const CACHE = 'whul-' + VERSION;

self.addEventListener('install', function (event) {{
  // Take over straight away rather than waiting for every window to close. A
  // standalone app window may never be closed, and a worker that waits for
  // that is a worker that never updates.
  self.skipWaiting();
}});

self.addEventListener('activate', function (event) {{
  event.waitUntil(
    caches.keys().then(function (names) {{
      return Promise.all(names.map(function (name) {{
        return name === CACHE ? null : caches.delete(name);
      }}));
    }}).then(function () {{
      return self.clients.claim();
    }})
  );
}});

self.addEventListener('fetch', function (event) {{
  var request = event.request;
  if (request.method !== 'GET') return;
  if (new URL(request.url).origin !== self.location.origin) return;

  event.respondWith(
    fetch(request).then(function (response) {{
      // Only a real answer is worth keeping. A 404 or a redirect cached here
      // would outlive whatever caused it.
      if (response && response.status === 200 && response.type === 'basic') {{
        var copy = response.clone();
        caches.open(CACHE).then(function (cache) {{
          cache.put(request, copy);
        }});
      }}
      return response;
    }}).catch(function () {{
      return caches.match(request).then(function (hit) {{
        if (hit) return hit;
        // A navigation with nothing cached for it still wants a page rather
        // than a browser error, so fall back to the standings.
        if (request.mode === 'navigate') return caches.match('index.html');
        return Response.error();
      }});
    }})
  );
}});
"""


#: What a page puts in its head. ``up`` is the climb to the site root, the same
#: prefix the stylesheet and the script already use.
def head(up: str = "") -> str:
    return f"""<link rel="manifest" href="{up}manifest.webmanifest">
<link rel="icon" href="{up}icon-192.png">
<link rel="apple-touch-icon" href="{up}icon-180.png">
<meta name="theme-color" content="{THEME_LIGHT}" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="{THEME_DARK}" media="(prefers-color-scheme: dark)">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="default">
<meta name="apple-mobile-web-app-title" content="{LEAGUE_ABBR}">"""
