"""nflverse data access.

The R scripts used ``nflreadr``; these read the same underlying nflverse assets
directly, which keeps the dependency free and language-agnostic.

``load_schedules`` and ``load_teams`` read from raw.githubusercontent rather than
github.com/.../raw/... -- the latter is 403-blocked through the agent proxy.
"""

from __future__ import annotations

import pandas as pd

RELEASES = "https://github.com/nflverse/nflverse-data/releases/download"
NFLDATA = "https://raw.githubusercontent.com/nflverse/nfldata/master/data"


#: nflverse retired the `player_stats` release; weekly stats now live under
#: `stats_player`, generated by nflfastR::calculate_stats(). The newer files use
#: `passing_interceptions` and `team` where the old ones used `interceptions` and
#: `recent_team` -- the candidate-column resolver in scoring/base.py covers both.
PLAYER_WEEK = f"{RELEASES}/stats_player/stats_player_week"
LEGACY_PLAYER_STATS = f"{RELEASES}/player_stats/player_stats"

FIRST_AVAILABLE_SEASON = 1999


def load_player_stats(seasons: list[int]) -> pd.DataFrame:
    """Weekly offensive player stats, one parquet per season.

    Falls back to the retired `player_stats` release if a season is missing from
    `stats_player`, so an upstream reshuffle degrades rather than breaks.
    """
    frames, missing = [], []
    for year in seasons:
        try:
            frames.append(pd.read_parquet(f"{PLAYER_WEEK}_{year}.parquet"))
            continue
        except Exception:
            pass
        try:
            frames.append(pd.read_parquet(f"{LEGACY_PLAYER_STATS}_{year}.parquet"))
        except Exception:
            # nflverse publishes a season's file once that season has played.
            # Asked for the current year in August, both releases 404, and the
            # raised error reads as a broken feed rather than as a season that
            # has not kicked off. A year nobody has played is not a failure;
            # every year being absent is, and _check_seasons says so.
            missing.append(year)
    _check_seasons(missing, seasons)
    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()


def _check_seasons(missing: list[int], seasons: list[int]) -> None:
    """A season not yet published is fine. All of them missing is not."""
    if missing and len(missing) == len(seasons):
        raise FileNotFoundError(
            f"nflverse has no player stats for {missing}. A season is published "
            f"once it has played, so this is expected before week one and a "
            f"broken feed at any other time."
        )
    if missing:
        print(f"  nflverse: no player stats published yet for {missing}",
              flush=True)


def load_schedules(seasons: list[int] | None = None) -> pd.DataFrame:
    """Game results for every season; optionally filtered."""
    df = pd.read_csv(f"{NFLDATA}/games.csv", low_memory=False)
    return df[df["season"].isin(seasons)].copy() if seasons else df


def load_teams(seasons: list[int] | None = None) -> pd.DataFrame:
    """Season-aware ``team_abbr`` -> division and full name.

    Divisions come from standings.csv because it tracks them per season, so
    relocations and realignments resolve correctly for historical years. The
    full name comes from teams.csv, which is season-aware for the same reason
    -- and it is needed because the feed identifies a team as "SEA" while a
    roster calls it "Seattle Seahawks", and nothing can match those two by
    spelling.
    """
    df = pd.read_csv(f"{NFLDATA}/standings.csv")
    if seasons:
        df = df[df["season"].isin(seasons)]
    teams = (
        df[["season", "team", "division"]]
        .rename(columns={"team": "team_abbr", "division": "team_division"})
        .drop_duplicates()
    )

    named = pd.read_csv(f"{NFLDATA}/teams.csv")[["season", "team", "full"]]
    named = named.rename(columns={"team": "team_abbr", "full": "team_name"})
    teams = teams.merge(named, on=["season", "team_abbr"], how="left")
    # A season the name table has not caught up with keeps the abbreviation
    # rather than a blank, which would match nothing and say nothing.
    teams["team_name"] = teams["team_name"].fillna(teams["team_abbr"])
    return teams.reset_index(drop=True)
